# Generated by Django 3.2 on 2021-07-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
    ]
